; generated by Slic3r 1.0.1 on 2014-05-16 at 18:00:16

; layer_height = 0.1
; perimeters = 2
; top_solid_layers = 3
; bottom_solid_layers = 5
; fill_density = 1
; perimeter_speed = 30
; infill_speed = 60
; travel_speed = 130
; nozzle_diameter = 0.4
; filament_diameter = 1.75
; extrusion_multiplier = 1
; perimeters extrusion width = 0.40mm
; infill extrusion width = 1.28mm
; solid infill extrusion width = 0.68mm
; top infill extrusion width = 0.68mm
; first layer extrusion width = 0.70mm

G21 ; set units to millimeters
M107
M190 S100 ; wait for bed temperature to be reached
M104 S230 ; set temperature
; --- MOVE THIS SECTION TO THE TOP AND DELETE THIS LINE ---
; filename = composition.3w
; machine = daVinciF10
; material = abs
; layer_height = 0.1
; total_layers = 173
; total_filament = 0.00
; extruder = 1
; --- END SECTION ---
M109 S230 ; wait for temperature to be reached
G90 ; use absolute coordinates
G92 E0
M82 ; use absolute distances for extrusion
G1 F1800.000 E-1.00000
G92 E0
